### ISSUE TITLE
[Feature Request] Output the identifier file as CSV / JSON?

### ISSUE THREAD

**Issue by stevieflow** [codeforIATI/activity-id-checker#3]
In the same way (albeit a much smaller file) https://org-id-finder.codeforiati.org/ has an output in csv format, could this service provide a list of the identifiers , too?

It *might* be something an analyst would be interested in using

It could also be something we could use with https://github.com/OpenDataServices/cove/issues/1339

**Comment by andylolz** [comment]
I’ve added a page with these downloads, though it currently isn’t linked from anywhere.
https://activity-id-checker.codeforiati.org/downloads/

The CSV just has one column I’m afraid!
