### ISSUE TITLE
SAVi view

### ISSUE THREAD

**Issue by notshi** [codeforIATI/activity-id-checker#5]
Hello!

We've made some changes to the SAVi view and it now has it's own url.
Thought it might be an option to use instead of the current one.

https://github.com/codeforIATI/activity-id-checker/blob/5ab28758d24890648070ff4e8adfb546eaa140a5/out/assets/js.js#L74

On that line, the url should be:

```html
https://d-portal.org/savi/?aid=
```

Here is the discussion about it ([link](https://github.com/devinit/D-Portal/issues/637#issuecomment-999257840)).

Wasn't sure if you'd prefer to use that so I didn't do a pull request.
Let me know if that's easier!

**Comment by andylolz** [comment]
Ooh – thanks for this. Yes, I’ll make the change.

I suspect this is likely to affect other links in the wild… It’s certainly not the end of the world, and it’s good that the old links don’t 404 (it’s just the theme that is missing).

**Comment by notshi** [comment]
Thanks, Andy! The change was an unavoidable one so I've been nudging links in the wild as I see them! (Not ideal but the least I could do)
